services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://YOUR_MONGO_USER:YOUR_MONGO_PASSWORD@mongodb:27017/YOUR_DB_NAME?authSource=admin
      - HUSKY=0
    volumes:
      - ../../:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=YOUR_MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=YOUR_MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=YOUR_MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=YOUR_MONGO_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://YOUR_MONGO_USER:YOUR_MONGO_PASSWORD@mongodb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=YOUR_ADMIN_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=YOUR_ADMIN_PASSWORD
    depends_on:
      - mongodb

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  portainer_data:
